# frozen_string_literal: true

module Straddle
  module Resources
    # Bridge connects customer bank accounts and creates paykeys from supported
    # provider tokens or bank account details.
    class Bridge
      # Some parameter documentations has been truncated, see
      # {Straddle::Models::BridgeCreateBankAccountPaykeyParams} for more details.
      #
      # Creates a paykey from a routing number, account number, and account type.
      #
      # @overload create_bank_account_paykey(account_number:, account_type:, customer_id:, routing_number:, config: nil, external_id: nil, metadata: nil, correlation_id: nil, idempotency_key: nil, request_id: nil, straddle_account_id: nil, request_options: {})
      #
      # @param account_number [String] Body param: Bank account number.
      #
      # @param account_type [Symbol, Straddle::Models::AccountType] Body param
      #
      # @param customer_id [String] Body param: Unique identifier for the customer associated with the paykey.
      #
      # @param routing_number [String] Body param: Bank routing number.
      #
      # @param config [Straddle::Models::PaykeyConfiguration] Body param
      #
      # @param external_id [String, nil] Body param: Unique identifier for the paykey in your system.
      #
      # @param metadata [Hash{Symbol=>String}, nil] Body param: Up to 20 user-defined key-value pairs associated with the paykey.
      #
      # @param correlation_id [String] Header param: Optional client-generated identifier for tracing a series of relat
      #
      # @param idempotency_key [String] Header param: Optional client-generated key for an idempotent request.
      #
      # @param request_id [String] Header param: Optional client-generated identifier for tracing one request.
      #
      # @param straddle_account_id [String] Header param: For platform requests, the embedded account UUID that sets the req
      #
      # @param request_options [Straddle::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Straddle::Models::PaykeyResponse]
      #
      # @see Straddle::Models::BridgeCreateBankAccountPaykeyParams
      def create_bank_account_paykey(params)
        parsed, options = Straddle::BridgeCreateBankAccountPaykeyParams.dump_request(params)
        header_params = {
          correlation_id: "correlation-id",
          idempotency_key: "idempotency-key",
          request_id: "request-id",
          straddle_account_id: "straddle-account-id"
        }
        @client.request(
          method: :post,
          path: "v1/bridge/bank_account",
          headers: parsed.slice(*header_params.keys).transform_keys(header_params),
          body: parsed.except(*header_params.keys),
          model: Straddle::PaykeyResponse,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {Straddle::Models::BridgeCreatePlaidPaykeyParams} for more details.
      #
      # Creates a paykey from a Plaid processor token.
      #
      # @overload create_plaid_paykey(customer_id:, plaid_token:, config: nil, external_id: nil, metadata: nil, correlation_id: nil, idempotency_key: nil, request_id: nil, straddle_account_id: nil, request_options: {})
      #
      # @param customer_id [String] Body param: Unique identifier for the customer associated with the paykey.
      #
      # @param plaid_token [String] Body param: Plaid processor token generated by your application for use with the
      #
      # @param config [Straddle::Models::PaykeyConfiguration] Body param
      #
      # @param external_id [String, nil] Body param: Unique identifier for the paykey in your system.
      #
      # @param metadata [Hash{Symbol=>String}, nil] Body param: Up to 20 user-defined key-value pairs associated with the paykey.
      #
      # @param correlation_id [String] Header param: Optional client-generated identifier for tracing a series of relat
      #
      # @param idempotency_key [String] Header param: Optional client-generated key for an idempotent request.
      #
      # @param request_id [String] Header param: Optional client-generated identifier for tracing one request.
      #
      # @param straddle_account_id [String] Header param: For platform requests, the embedded account UUID that sets the req
      #
      # @param request_options [Straddle::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Straddle::Models::PaykeyResponse]
      #
      # @see Straddle::Models::BridgeCreatePlaidPaykeyParams
      def create_plaid_paykey(params)
        parsed, options = Straddle::BridgeCreatePlaidPaykeyParams.dump_request(params)
        header_params = {
          correlation_id: "correlation-id",
          idempotency_key: "idempotency-key",
          request_id: "request-id",
          straddle_account_id: "straddle-account-id"
        }
        @client.request(
          method: :post,
          path: "v1/bridge/plaid",
          headers: parsed.slice(*header_params.keys).transform_keys(header_params),
          body: parsed.except(*header_params.keys),
          model: Straddle::PaykeyResponse,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {Straddle::Models::BridgeCreateQuilttPaykeyParams} for more details.
      #
      # Creates a paykey from a Quiltt processor token.
      #
      # @overload create_quiltt_paykey(customer_id:, quiltt_token:, config: nil, external_id: nil, metadata: nil, correlation_id: nil, idempotency_key: nil, request_id: nil, straddle_account_id: nil, request_options: {})
      #
      # @param customer_id [String] Body param: Unique identifier for the customer associated with the paykey.
      #
      # @param quiltt_token [String] Body param: Quiltt processor token generated by your application for use with th
      #
      # @param config [Straddle::Models::PaykeyConfiguration] Body param
      #
      # @param external_id [String, nil] Body param: Unique identifier for the paykey in your system.
      #
      # @param metadata [Hash{Symbol=>String}, nil] Body param: Up to 20 user-defined key-value pairs associated with the paykey.
      #
      # @param correlation_id [String] Header param: Optional client-generated identifier for tracing a series of relat
      #
      # @param idempotency_key [String] Header param: Optional client-generated key for an idempotent request.
      #
      # @param request_id [String] Header param: Optional client-generated identifier for tracing one request.
      #
      # @param straddle_account_id [String] Header param: For platform requests, the embedded account UUID that sets the req
      #
      # @param request_options [Straddle::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Straddle::Models::RevealedPaykeyResponse]
      #
      # @see Straddle::Models::BridgeCreateQuilttPaykeyParams
      def create_quiltt_paykey(params)
        parsed, options = Straddle::BridgeCreateQuilttPaykeyParams.dump_request(params)
        header_params = {
          correlation_id: "correlation-id",
          idempotency_key: "idempotency-key",
          request_id: "request-id",
          straddle_account_id: "straddle-account-id"
        }
        @client.request(
          method: :post,
          path: "v1/bridge/quiltt",
          headers: parsed.slice(*header_params.keys).transform_keys(header_params),
          body: parsed.except(*header_params.keys),
          model: Straddle::RevealedPaykeyResponse,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {Straddle::Models::BridgeCreateTokenParams} for more details.
      #
      # Creates a session token for the Bridge widget.
      #
      # @overload create_token(customer_id:, config: nil, external_id: nil, correlation_id: nil, idempotency_key: nil, request_id: nil, straddle_account_id: nil, request_options: {})
      #
      # @param customer_id [String] Body param: Unique identifier for the customer associated with the Bridge sessio
      #
      # @param config [Straddle::Models::PaykeyConfiguration] Body param
      #
      # @param external_id [String, nil] Body param: Unique identifier for the paykey in your system.
      #
      # @param correlation_id [String] Header param: Optional client-generated identifier for tracing a series of relat
      #
      # @param idempotency_key [String] Header param: Optional client-generated key for an idempotent request.
      #
      # @param request_id [String] Header param: Optional client-generated identifier for tracing one request.
      #
      # @param straddle_account_id [String] Header param: For platform requests, the embedded account UUID that sets the req
      #
      # @param request_options [Straddle::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Straddle::Models::BridgeTokenResponse]
      #
      # @see Straddle::Models::BridgeCreateTokenParams
      def create_token(params)
        parsed, options = Straddle::BridgeCreateTokenParams.dump_request(params)
        header_params = {
          correlation_id: "correlation-id",
          idempotency_key: "idempotency-key",
          request_id: "request-id",
          straddle_account_id: "straddle-account-id"
        }
        @client.request(
          method: :post,
          path: "v1/bridge/initialize",
          headers: parsed.slice(*header_params.keys).transform_keys(header_params),
          body: parsed.except(*header_params.keys),
          model: Straddle::BridgeTokenResponse,
          options: options
        )
      end

      # @api private
      #
      # @param client [Straddle::Client]
      def initialize(client:)
        @client = client
      end
    end
  end
end
