module Straddle
  module Models
    type account_list =
      {
        data: ::Array[Straddle::Account],
        meta: Straddle::PageMetadata,
        response_type: Straddle::Models::AccountList::response_type
      }

    class AccountList < Straddle::Internal::Type::BaseModel
      attr_accessor data: ::Array[Straddle::Account]

      attr_accessor meta: Straddle::PageMetadata

      attr_accessor response_type: Straddle::Models::AccountList::response_type

      def initialize: (
        data: ::Array[Straddle::Account],
        meta: Straddle::PageMetadata,
        response_type: Straddle::Models::AccountList::response_type
      ) -> void

      def to_hash: -> {
        data: ::Array[Straddle::Account],
        meta: Straddle::PageMetadata,
        response_type: Straddle::Models::AccountList::response_type
      }

      type response_type = :object | :array | :error | :none

      module ResponseType
        extend Straddle::Internal::Type::Enum

        OBJECT: :object
        ARRAY: :array
        ERROR: :error
        NONE: :none

        def self?.values: -> ::Array[Straddle::Models::AccountList::response_type]
      end
    end
  end
end
