module Straddle
  module Models
    type account_support_channels =
      { email: String?, phone: String?, url: String? }

    class AccountSupportChannels < Straddle::Internal::Type::BaseModel
      attr_accessor email: String?

      attr_accessor phone: String?

      attr_accessor url: String?

      def initialize: (?email: String?, ?phone: String?, ?url: String?) -> void

      def to_hash: -> { email: String?, phone: String?, url: String? }
    end
  end
end
