module Straddle
  module Models
    type customer =
      {
        id: String,
        created_at: Time,
        email: String,
        name: String,
        phone: String,
        status: Straddle::Models::customer_status,
        type: Straddle::Models::customer_type,
        updated_at: Time,
        address: Straddle::CustomerAddress?,
        compliance_profile: Straddle::Models::compliance_profile?,
        config: Straddle::CustomerConfiguration,
        device: Straddle::MaskedCustomerDevice,
        external_id: String?,
        metadata: ::Hash[Symbol, String]?
      }

    class Customer < Straddle::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor email: String

      attr_accessor name: String

      attr_accessor phone: String

      attr_accessor status: Straddle::Models::customer_status

      attr_accessor type: Straddle::Models::customer_type

      attr_accessor updated_at: Time

      attr_accessor address: Straddle::CustomerAddress?

      attr_accessor compliance_profile: Straddle::Models::compliance_profile?

      attr_reader config: Straddle::CustomerConfiguration?

      def config=: (
        Straddle::CustomerConfiguration
      ) -> Straddle::CustomerConfiguration

      attr_reader device: Straddle::MaskedCustomerDevice?

      def device=: (
        Straddle::MaskedCustomerDevice
      ) -> Straddle::MaskedCustomerDevice

      attr_accessor external_id: String?

      attr_accessor metadata: ::Hash[Symbol, String]?

      def initialize: (
        id: String,
        created_at: Time,
        email: String,
        name: String,
        phone: String,
        status: Straddle::Models::customer_status,
        type: Straddle::Models::customer_type,
        updated_at: Time,
        ?address: Straddle::CustomerAddress?,
        ?compliance_profile: Straddle::Models::compliance_profile?,
        ?config: Straddle::CustomerConfiguration,
        ?device: Straddle::MaskedCustomerDevice,
        ?external_id: String?,
        ?metadata: ::Hash[Symbol, String]?
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        email: String,
        name: String,
        phone: String,
        status: Straddle::Models::customer_status,
        type: Straddle::Models::customer_type,
        updated_at: Time,
        address: Straddle::CustomerAddress?,
        compliance_profile: Straddle::Models::compliance_profile?,
        config: Straddle::CustomerConfiguration,
        device: Straddle::MaskedCustomerDevice,
        external_id: String?,
        metadata: ::Hash[Symbol, String]?
      }
    end
  end
end
