module Straddle
  module Models
    type funding_event_created_v1_webhook_event =
      {
        account_id: String,
        data: Straddle::FundingEventCreatedV1WebhookEvent::Data,
        event_id: String,
        event_type: String
      }

    class FundingEventCreatedV1WebhookEvent < Straddle::Internal::Type::BaseModel
      attr_accessor account_id: String

      attr_accessor data: Straddle::FundingEventCreatedV1WebhookEvent::Data

      attr_accessor event_id: String

      attr_accessor event_type: String

      def initialize: (
        account_id: String,
        data: Straddle::FundingEventCreatedV1WebhookEvent::Data,
        event_id: String,
        event_type: String
      ) -> void

      def to_hash: -> {
        account_id: String,
        data: Straddle::FundingEventCreatedV1WebhookEvent::Data,
        event_id: String,
        event_type: String
      }

      type data =
        {
          id: String,
          amount: Integer,
          created_at: Time,
          direction: Straddle::Models::funding_event_transfer_direction,
          event_type: Straddle::Models::funding_event_type,
          payment_count: Integer,
          status_history: ::Array[Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusHistory],
          trace_ids: ::Hash[Symbol, String],
          transfer_date: Date,
          updated_at: Time,
          status: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::status,
          status_details: Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusDetails
        }

      class Data < Straddle::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount: Integer

        attr_accessor created_at: Time

        attr_accessor direction: Straddle::Models::funding_event_transfer_direction

        attr_accessor event_type: Straddle::Models::funding_event_type

        attr_accessor payment_count: Integer

        attr_accessor status_history: ::Array[Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusHistory]

        attr_accessor trace_ids: ::Hash[Symbol, String]

        attr_accessor transfer_date: Date

        attr_accessor updated_at: Time

        attr_reader status: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::status?

        def status=: (
          Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::status
        ) -> Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::status

        attr_reader status_details: Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusDetails?

        def status_details=: (
          Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusDetails
        ) -> Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusDetails

        def initialize: (
          id: String,
          amount: Integer,
          created_at: Time,
          direction: Straddle::Models::funding_event_transfer_direction,
          event_type: Straddle::Models::funding_event_type,
          payment_count: Integer,
          status_history: ::Array[Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusHistory],
          trace_ids: ::Hash[Symbol, String],
          transfer_date: Date,
          updated_at: Time,
          ?status: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::status,
          ?status_details: Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusDetails
        ) -> void

        def to_hash: -> {
          id: String,
          amount: Integer,
          created_at: Time,
          direction: Straddle::Models::funding_event_transfer_direction,
          event_type: Straddle::Models::funding_event_type,
          payment_count: Integer,
          status_history: ::Array[Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusHistory],
          trace_ids: ::Hash[Symbol, String],
          transfer_date: Date,
          updated_at: Time,
          status: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::status,
          status_details: Straddle::FundingEventCreatedV1WebhookEvent::Data::StatusDetails
        }

        type status_history =
          {
            changed_at: Time,
            message: String,
            reason: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::reason,
            source: Straddle::Models::payment_status_source,
            status: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::status,
            code: String?
          }

        class StatusHistory < Straddle::Internal::Type::BaseModel
          attr_accessor changed_at: Time

          attr_accessor message: String

          attr_accessor reason: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::reason

          attr_accessor source: Straddle::Models::payment_status_source

          attr_accessor status: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::status

          attr_accessor code: String?

          def initialize: (
            changed_at: Time,
            message: String,
            reason: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::reason,
            source: Straddle::Models::payment_status_source,
            status: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::status,
            ?code: String?
          ) -> void

          def to_hash: -> {
            changed_at: Time,
            message: String,
            reason: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::reason,
            source: Straddle::Models::payment_status_source,
            status: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::status,
            code: String?
          }

          type reason =
            :insufficient_funds
            | :closed_bank_account
            | :invalid_bank_account
            | :invalid_routing
            | :disputed
            | :payment_stopped
            | :owner_deceased
            | :frozen_bank_account
            | :risk_review
            | :fraudulent
            | :duplicate_entry
            | :invalid_paykey
            | :payment_blocked
            | :amount_too_large
            | :too_many_attempts
            | :internal_system_error
            | :user_request
            | :ok
            | :other_network_return
            | :payout_refused
            | :validating
            | :auto_hold

          module Reason
            extend Straddle::Internal::Type::Enum

            INSUFFICIENT_FUNDS: :insufficient_funds
            CLOSED_BANK_ACCOUNT: :closed_bank_account
            INVALID_BANK_ACCOUNT: :invalid_bank_account
            INVALID_ROUTING: :invalid_routing
            DISPUTED: :disputed
            PAYMENT_STOPPED: :payment_stopped
            OWNER_DECEASED: :owner_deceased
            FROZEN_BANK_ACCOUNT: :frozen_bank_account
            RISK_REVIEW: :risk_review
            FRAUDULENT: :fraudulent
            DUPLICATE_ENTRY: :duplicate_entry
            INVALID_PAYKEY: :invalid_paykey
            PAYMENT_BLOCKED: :payment_blocked
            AMOUNT_TOO_LARGE: :amount_too_large
            TOO_MANY_ATTEMPTS: :too_many_attempts
            INTERNAL_SYSTEM_ERROR: :internal_system_error
            USER_REQUEST: :user_request
            OK: :ok
            OTHER_NETWORK_RETURN: :other_network_return
            PAYOUT_REFUSED: :payout_refused
            VALIDATING: :validating
            AUTO_HOLD: :auto_hold

            def self?.values: -> ::Array[Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::reason]
          end

          type status =
            :created
            | :scheduled
            | :failed
            | :cancelled
            | :on_hold
            | :pending
            | :paid
            | :reversed

          module Status
            extend Straddle::Internal::Type::Enum

            CREATED: :created
            SCHEDULED: :scheduled
            FAILED: :failed
            CANCELLED: :cancelled
            ON_HOLD: :on_hold
            PENDING: :pending
            PAID: :paid
            REVERSED: :reversed

            def self?.values: -> ::Array[Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusHistory::status]
          end
        end

        type status =
          :created
          | :scheduled
          | :failed
          | :cancelled
          | :on_hold
          | :pending
          | :paid
          | :reversed

        module Status
          extend Straddle::Internal::Type::Enum

          CREATED: :created
          SCHEDULED: :scheduled
          FAILED: :failed
          CANCELLED: :cancelled
          ON_HOLD: :on_hold
          PENDING: :pending
          PAID: :paid
          REVERSED: :reversed

          def self?.values: -> ::Array[Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::status]
        end

        type status_details =
          {
            changed_at: Time,
            code: String?,
            message: String,
            reason: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusDetails::reason,
            source: Straddle::Models::payment_status_source
          }

        class StatusDetails < Straddle::Internal::Type::BaseModel
          attr_accessor changed_at: Time

          attr_accessor code: String?

          attr_accessor message: String

          attr_accessor reason: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusDetails::reason

          attr_accessor source: Straddle::Models::payment_status_source

          def initialize: (
            changed_at: Time,
            code: String?,
            message: String,
            reason: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusDetails::reason,
            source: Straddle::Models::payment_status_source
          ) -> void

          def to_hash: -> {
            changed_at: Time,
            code: String?,
            message: String,
            reason: Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusDetails::reason,
            source: Straddle::Models::payment_status_source
          }

          type reason =
            :insufficient_funds
            | :closed_bank_account
            | :invalid_bank_account
            | :invalid_routing
            | :disputed
            | :payment_stopped
            | :owner_deceased
            | :frozen_bank_account
            | :risk_review
            | :fraudulent
            | :duplicate_entry
            | :invalid_paykey
            | :payment_blocked
            | :amount_too_large
            | :too_many_attempts
            | :internal_system_error
            | :user_request
            | :ok
            | :other_network_return
            | :payout_refused
            | :validating
            | :auto_hold

          module Reason
            extend Straddle::Internal::Type::Enum

            INSUFFICIENT_FUNDS: :insufficient_funds
            CLOSED_BANK_ACCOUNT: :closed_bank_account
            INVALID_BANK_ACCOUNT: :invalid_bank_account
            INVALID_ROUTING: :invalid_routing
            DISPUTED: :disputed
            PAYMENT_STOPPED: :payment_stopped
            OWNER_DECEASED: :owner_deceased
            FROZEN_BANK_ACCOUNT: :frozen_bank_account
            RISK_REVIEW: :risk_review
            FRAUDULENT: :fraudulent
            DUPLICATE_ENTRY: :duplicate_entry
            INVALID_PAYKEY: :invalid_paykey
            PAYMENT_BLOCKED: :payment_blocked
            AMOUNT_TOO_LARGE: :amount_too_large
            TOO_MANY_ATTEMPTS: :too_many_attempts
            INTERNAL_SYSTEM_ERROR: :internal_system_error
            USER_REQUEST: :user_request
            OK: :ok
            OTHER_NETWORK_RETURN: :other_network_return
            PAYOUT_REFUSED: :payout_refused
            VALIDATING: :validating
            AUTO_HOLD: :auto_hold

            def self?.values: -> ::Array[Straddle::Models::FundingEventCreatedV1WebhookEvent::Data::StatusDetails::reason]
          end
        end
      end
    end
  end
end
