module Straddle
  module Models
    type funding_event_list_payments_params =
      {
        id: String,
        default_page_size: Integer,
        default_sort: Straddle::Models::FundingEventListPaymentsParams::default_sort,
        default_sort_order: Straddle::Models::sort_order,
        include_metadata: bool,
        page_number: Integer,
        page_size: Integer,
        sort_by: Straddle::Models::FundingEventListPaymentsParams::sort_by,
        sort_order: Straddle::Models::sort_order,
        correlation_id: String,
        request_id: String,
        straddle_account_id: String
      }
      & Straddle::Internal::Type::request_parameters

    class FundingEventListPaymentsParams < Straddle::Internal::Type::BaseModel
      extend Straddle::Internal::Type::RequestParameters::Converter
      include Straddle::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader default_page_size: Integer?

      def default_page_size=: (Integer) -> Integer

      attr_reader default_sort: Straddle::Models::FundingEventListPaymentsParams::default_sort?

      def default_sort=: (
        Straddle::Models::FundingEventListPaymentsParams::default_sort
      ) -> Straddle::Models::FundingEventListPaymentsParams::default_sort

      attr_reader default_sort_order: Straddle::Models::sort_order?

      def default_sort_order=: (
        Straddle::Models::sort_order
      ) -> Straddle::Models::sort_order

      attr_reader include_metadata: bool?

      def include_metadata=: (bool) -> bool

      attr_reader page_number: Integer?

      def page_number=: (Integer) -> Integer

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader sort_by: Straddle::Models::FundingEventListPaymentsParams::sort_by?

      def sort_by=: (
        Straddle::Models::FundingEventListPaymentsParams::sort_by
      ) -> Straddle::Models::FundingEventListPaymentsParams::sort_by

      attr_reader sort_order: Straddle::Models::sort_order?

      def sort_order=: (
        Straddle::Models::sort_order
      ) -> Straddle::Models::sort_order

      attr_reader correlation_id: String?

      def correlation_id=: (String) -> String

      attr_reader request_id: String?

      def request_id=: (String) -> String

      attr_reader straddle_account_id: String?

      def straddle_account_id=: (String) -> String

      def initialize: (
        id: String,
        ?default_page_size: Integer,
        ?default_sort: Straddle::Models::FundingEventListPaymentsParams::default_sort,
        ?default_sort_order: Straddle::Models::sort_order,
        ?include_metadata: bool,
        ?page_number: Integer,
        ?page_size: Integer,
        ?sort_by: Straddle::Models::FundingEventListPaymentsParams::sort_by,
        ?sort_order: Straddle::Models::sort_order,
        ?correlation_id: String,
        ?request_id: String,
        ?straddle_account_id: String,
        ?request_options: Straddle::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        default_page_size: Integer,
        default_sort: Straddle::Models::FundingEventListPaymentsParams::default_sort,
        default_sort_order: Straddle::Models::sort_order,
        include_metadata: bool,
        page_number: Integer,
        page_size: Integer,
        sort_by: Straddle::Models::FundingEventListPaymentsParams::sort_by,
        sort_order: Straddle::Models::sort_order,
        correlation_id: String,
        request_id: String,
        straddle_account_id: String,
        request_options: Straddle::RequestOptions
      }

      type default_sort = :created_at | :payment_date | :effective_at | :id

      module DefaultSort
        extend Straddle::Internal::Type::Enum

        CREATED_AT: :created_at
        PAYMENT_DATE: :payment_date
        EFFECTIVE_AT: :effective_at
        ID: :id

        def self?.values: -> ::Array[Straddle::Models::FundingEventListPaymentsParams::default_sort]
      end

      type sort_by = :created_at | :payment_date | :effective_at | :id

      module SortBy
        extend Straddle::Internal::Type::Enum

        CREATED_AT: :created_at
        PAYMENT_DATE: :payment_date
        EFFECTIVE_AT: :effective_at
        ID: :id

        def self?.values: -> ::Array[Straddle::Models::FundingEventListPaymentsParams::sort_by]
      end
    end
  end
end
