module Straddle
  module Models
    type paykey_status =
      :pending | :active | :inactive | :rejected | :review | :blocked

    module PaykeyStatus
      extend Straddle::Internal::Type::Enum

      PENDING: :pending
      ACTIVE: :active
      INACTIVE: :inactive
      REJECTED: :rejected
      REVIEW: :review
      BLOCKED: :blocked

      def self?.values: -> ::Array[Straddle::Models::paykey_status]
    end
  end
end
