module Straddle
  module Models
    type payment_status =
      :created
      | :scheduled
      | :failed
      | :cancelled
      | :on_hold
      | :pending
      | :paid
      | :reversed
      | :validating

    module PaymentStatus
      extend Straddle::Internal::Type::Enum

      CREATED: :created
      SCHEDULED: :scheduled
      FAILED: :failed
      CANCELLED: :cancelled
      ON_HOLD: :on_hold
      PENDING: :pending
      PAID: :paid
      REVERSED: :reversed
      VALIDATING: :validating

      def self?.values: -> ::Array[Straddle::Models::payment_status]
    end
  end
end
