module Straddle
  module Models
    type representative_status_detail =
      {
        code: String,
        message: String,
        reason: Straddle::Models::RepresentativeStatusDetail::reason,
        source: Straddle::Models::RepresentativeStatusDetail::source
      }

    class RepresentativeStatusDetail < Straddle::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor message: String

      attr_accessor reason: Straddle::Models::RepresentativeStatusDetail::reason

      attr_accessor source: Straddle::Models::RepresentativeStatusDetail::source

      def initialize: (
        code: String,
        message: String,
        reason: Straddle::Models::RepresentativeStatusDetail::reason,
        source: Straddle::Models::RepresentativeStatusDetail::source
      ) -> void

      def to_hash: -> {
        code: String,
        message: String,
        reason: Straddle::Models::RepresentativeStatusDetail::reason,
        source: Straddle::Models::RepresentativeStatusDetail::source
      }

      type reason =
        :unverified
        | :in_review
        | :pending
        | :stuck
        | :verified
        | :failed_verification
        | :disabled
        | :new

      module Reason
        extend Straddle::Internal::Type::Enum

        UNVERIFIED: :unverified
        IN_REVIEW: :in_review
        PENDING: :pending
        STUCK: :stuck
        VERIFIED: :verified
        FAILED_VERIFICATION: :failed_verification
        DISABLED: :disabled
        NEW: :new

        def self?.values: -> ::Array[Straddle::Models::RepresentativeStatusDetail::reason]
      end

      type source = :watchtower

      module Source
        extend Straddle::Internal::Type::Enum

        WATCHTOWER: :watchtower

        def self?.values: -> ::Array[Straddle::Models::RepresentativeStatusDetail::source]
      end
    end
  end
end
