module Straddle
  module Models
    type unmasked_payout_response =
      {
        data: Straddle::UnmaskedPayout,
        meta: Straddle::ResponseMetadata,
        response_type: Straddle::Models::response_type
      }

    class UnmaskedPayoutResponse < Straddle::Internal::Type::BaseModel
      attr_accessor data: Straddle::UnmaskedPayout

      attr_accessor meta: Straddle::ResponseMetadata

      attr_accessor response_type: Straddle::Models::response_type

      def initialize: (
        data: Straddle::UnmaskedPayout,
        meta: Straddle::ResponseMetadata,
        response_type: Straddle::Models::response_type
      ) -> void

      def to_hash: -> {
        data: Straddle::UnmaskedPayout,
        meta: Straddle::ResponseMetadata,
        response_type: Straddle::Models::response_type
      }
    end
  end
end
