module Straddle
  module Models
    type unwrap_webhook_event =
      Straddle::AccountCreatedV1WebhookEvent
      | Straddle::AccountEventV1WebhookEvent
      | Straddle::RepresentativeEventV1WebhookEvent
      | Straddle::RepresentativeCreatedV1WebhookEvent
      | Straddle::LinkedBankAccountEventV1WebhookEvent
      | Straddle::LinkedBankAccountCreatedV1WebhookEvent
      | Straddle::CapabilityRequestEventV1WebhookEvent
      | Straddle::CapabilityRequestCreatedV1WebhookEvent
      | Straddle::CustomerEventV1WebhookEvent
      | Straddle::CustomerCreatedV1WebhookEvent
      | Straddle::PaykeyEventV1WebhookEvent
      | Straddle::PaykeyCreatedV1WebhookEvent
      | Straddle::ChargeCreatedV1WebhookEvent
      | Straddle::ChargeEventV1WebhookEvent
      | Straddle::PayoutCreatedV1WebhookEvent
      | Straddle::PayoutEventV1WebhookEvent
      | Straddle::PlatformEventV1WebhookEvent
      | Straddle::PlatformCreatedV1WebhookEvent
      | Straddle::UserEventV1WebhookEvent
      | Straddle::UserCreatedV1WebhookEvent
      | Straddle::FundingEventCreatedV1WebhookEvent
      | Straddle::FundingEventEventV1WebhookEvent

    module UnwrapWebhookEvent
      extend Straddle::Internal::Type::Union

      def self?.variants: -> ::Array[Straddle::Models::unwrap_webhook_event]
    end
  end
end
