# frozen_string_literal: true

# Code generated by Scalar SDK Generator. DO NOT EDIT.
require "json"
require "stringio"
require "time"

root = File.exist?(File.join(__dir__, "lib", "straddle.rb")) ? __dir__ : File.expand_path("..", __dir__)
$LOAD_PATH.unshift(File.join(root, "lib"))
require "straddle"

# Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
# Run it from this repo with `ruby tests/smoke-test.rb`. The generator also runs this file
# against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
client = Straddle::Client.new(max_retries: 0, timeout: 30)

cases = [
  {
    operation: "create",
    method: "POST",
    path: "/v1/accounts",
    label: "required params",
    run: -> do
      client.accounts.create(
        {
          access_level: "standard",
          account_type: "business",
          business_profile: StringIO.new("smoke-test"),
          organization_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/accounts",
    label: "all params",
    run: -> do
      client.accounts.create(
        {
          access_level: "standard",
          account_type: "business",
          business_profile: StringIO.new("smoke-test"),
          organization_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          external_id: "",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/accounts/{account_id}",
    label: "required params",
    run: -> { client.accounts.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/accounts/{account_id}",
    label: "all params",
    run: -> do
      client.accounts.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {correlation_id: "correlation_id", request_id: "request_id"}
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/accounts/{account_id}",
    label: "required params",
    run: -> do
      client.accounts.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {business_profile: StringIO.new("smoke-test")}
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/accounts/{account_id}",
    label: "all params",
    run: -> do
      client.accounts.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          business_profile: StringIO.new("smoke-test"),
          external_id: "",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/accounts",
    label: "required params",
    run: -> { client.accounts.list({page_number: 1, page_size: 100, sort_by: "id", sort_order: "asc"}) }
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/accounts",
    label: "all params",
    run: -> do
      client.accounts.list(
        {
          external_id: "external_id",
          page_number: 1,
          page_size: 100,
          search_text: "search_text",
          sort_by: "id",
          sort_order: "asc",
          status: "created",
          type: "business",
          correlation_id: "correlation_id",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "onboard",
    method: "POST",
    path: "/v1/accounts/{account_id}/onboard",
    label: "required params",
    run: -> do
      client.accounts.onboard(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          terms_of_service: {
            "accepted_date" => "2024-01-01T00:00:00.000Z",
            "agreement_url" => "",
            "agreement_type" => "embedded"
          }
        }
      )
    end
  },
  {
    operation: "onboard",
    method: "POST",
    path: "/v1/accounts/{account_id}/onboard",
    label: "all params",
    run: -> do
      client.accounts.onboard(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          terms_of_service: {
            "accepted_date" => "2024-01-01T00:00:00.000Z",
            "accepted_ip" => "",
            "accepted_user_agent" => "",
            "agreement_url" => "",
            "agreement_type" => "embedded"
          },
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "simulateOnboarding",
    method: "POST",
    path: "/v1/accounts/{account_id}/simulate",
    label: "required params",
    run: -> { client.accounts.simulate_onboarding("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "simulateOnboarding",
    method: "POST",
    path: "/v1/accounts/{account_id}/simulate",
    label: "all params",
    run: -> do
      client.accounts.simulate_onboarding(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          final_status: "onboarding",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/accounts/{account_id}/capability_requests",
    label: "required params",
    run: -> { client.capability_requests.create("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/accounts/{account_id}/capability_requests",
    label: "all params",
    run: -> do
      client.capability_requests.create(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          businesses: {
            "enable" => false
          },
          charges: {
            "enable" => false,
            "max_amount" => 0,
            "daily_amount" => 0,
            "monthly_count" => 0,
            "monthly_amount" => 0
          },
          individuals: {
            "enable" => false
          },
          internet: {
            "enable" => false
          },
          payouts: {
            "enable" => false,
            "max_amount" => 0,
            "daily_amount" => 0,
            "monthly_count" => 0,
            "monthly_amount" => 0
          },
          signed_agreement: {
            "enable" => false
          },
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/accounts/{account_id}/capability_requests",
    label: "required params",
    run: -> do
      client.capability_requests.list(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {page_number: 1, page_size: 100, sort_by: "id", sort_order: "asc"}
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/accounts/{account_id}/capability_requests",
    label: "all params",
    run: -> do
      client.capability_requests.list(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          category: "payment_type",
          page_number: 1,
          page_size: 100,
          sort_by: "id",
          sort_order: "asc",
          status: "active",
          type: "charges",
          correlation_id: "correlation_id",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/linked_bank_accounts",
    label: "required params",
    run: -> do
      client.linked_bank_accounts.create(
        {bank_account: {"account_holder" => "", "routing_number" => "xxxxxxxxx", "account_number" => ""}}
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/linked_bank_accounts",
    label: "all params",
    run: -> do
      client.linked_bank_accounts.create(
        {
          bank_account: {
            "account_holder" => "",
            "routing_number" => "xxxxxxxxx",
            "account_number" => ""
          },
          account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          description: "",
          metadata: {},
          platform_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          purposes: [],
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/linked_bank_accounts/{linked_bank_account_id}",
    label: "required params",
    run: -> { client.linked_bank_accounts.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/linked_bank_accounts/{linked_bank_account_id}",
    label: "all params",
    run: -> do
      client.linked_bank_accounts.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {correlation_id: "correlation_id", request_id: "request_id"}
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/linked_bank_accounts/{linked_bank_account_id}",
    label: "required params",
    run: -> do
      client.linked_bank_accounts.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {bank_account: {"account_holder" => "", "routing_number" => "xxxxxxxxx", "account_number" => ""}}
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/linked_bank_accounts/{linked_bank_account_id}",
    label: "all params",
    run: -> do
      client.linked_bank_accounts.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          bank_account: {
            "account_holder" => "",
            "routing_number" => "xxxxxxxxx",
            "account_number" => ""
          },
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/linked_bank_accounts",
    label: "required params",
    run: -> do
      client.linked_bank_accounts.list({page_number: 1, page_size: 100, sort_by: "id", sort_order: "asc"})
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/linked_bank_accounts",
    label: "all params",
    run: -> do
      client.linked_bank_accounts.list(
        {
          account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          level: "account",
          page_number: 1,
          page_size: 100,
          purpose: "charges",
          sort_by: "id",
          sort_order: "asc",
          status: "created",
          correlation_id: "correlation_id",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "cancel",
    method: "PATCH",
    path: "/v1/linked_bank_accounts/{linked_bank_account_id}/cancel",
    label: "required params",
    run: -> { client.linked_bank_accounts.cancel("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "cancel",
    method: "PATCH",
    path: "/v1/linked_bank_accounts/{linked_bank_account_id}/cancel",
    label: "all params",
    run: -> do
      client.linked_bank_accounts.cancel(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {correlation_id: "correlation_id", idempotency_key: "idempotency_key", request_id: "request_id"}
      )
    end
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/linked_bank_accounts/{linked_bank_account_id}/unmask",
    label: "required params",
    run: -> { client.linked_bank_accounts.list_unmasked("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/linked_bank_accounts/{linked_bank_account_id}/unmask",
    label: "all params",
    run: -> do
      client.linked_bank_accounts.list_unmasked(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {correlation_id: "correlation_id", request_id: "request_id"}
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/organizations",
    label: "required params",
    run: -> { client.organizations.create({name: ""}) }
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/organizations",
    label: "all params",
    run: -> do
      client.organizations.create(
        {
          name: "",
          external_id: "",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/organizations/{organization_id}",
    label: "required params",
    run: -> { client.organizations.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/organizations/{organization_id}",
    label: "all params",
    run: -> do
      client.organizations.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {correlation_id: "correlation_id", request_id: "request_id"}
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/organizations",
    label: "required params",
    run: -> do
      client.organizations.list({page_number: 1, page_size: 100, sort_by: "id", sort_order: "asc"})
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/organizations",
    label: "all params",
    run: -> do
      client.organizations.list(
        {
          external_id: "external_id",
          name: "name",
          page_number: 1,
          page_size: 100,
          sort_by: "id",
          sort_order: "asc",
          correlation_id: "correlation_id",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/representatives",
    label: "required params",
    run: -> do
      client.representatives.create(
        {
          account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          dob: "1980-01-01",
          email: "ron.swanson@pawnee.com",
          first_name: "",
          last_name: "",
          mobile_number: "+12128675309",
          relationship: {
            "primary" => false,
            "control" => false,
            "owner" => false
          },
          ssn_last4: "1234"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/representatives",
    label: "all params",
    run: -> do
      client.representatives.create(
        {
          account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          dob: "1980-01-01",
          email: "ron.swanson@pawnee.com",
          first_name: "",
          last_name: "",
          mobile_number: "+12128675309",
          relationship: {
            "primary" => false,
            "control" => false,
            "owner" => false,
            "percent_ownership" => 0,
            "title" => ""
          },
          ssn_last4: "1234",
          external_id: "",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/representatives/{representative_id}",
    label: "required params",
    run: -> { client.representatives.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/representatives/{representative_id}",
    label: "all params",
    run: -> do
      client.representatives.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {correlation_id: "correlation_id", request_id: "request_id"}
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/representatives/{representative_id}",
    label: "required params",
    run: -> do
      client.representatives.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          dob: "1980-01-01",
          email: "ron.swanson@pawnee.com",
          first_name: "Ron",
          last_name: "Swanson",
          mobile_number: "+12128675309",
          relationship: {
            "primary" => false,
            "control" => false,
            "owner" => false
          },
          ssn_last4: "1234"
        }
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/representatives/{representative_id}",
    label: "all params",
    run: -> do
      client.representatives.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          dob: "1980-01-01",
          email: "ron.swanson@pawnee.com",
          first_name: "Ron",
          last_name: "Swanson",
          mobile_number: "+12128675309",
          relationship: {
            "primary" => false,
            "control" => false,
            "owner" => false,
            "percent_ownership" => 0,
            "title" => ""
          },
          ssn_last4: "1234",
          external_id: "",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/representatives",
    label: "required params",
    run: -> do
      client.representatives.list({page_number: 1, page_size: 100, sort_by: "id", sort_order: "asc"})
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/representatives",
    label: "all params",
    run: -> do
      client.representatives.list(
        {
          account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          level: "account",
          organization_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          page_number: 1,
          page_size: 100,
          platform_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          sort_by: "id",
          sort_order: "asc",
          correlation_id: "correlation_id",
          request_id: "request_id"
        }
      )
    end
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/representatives/{representative_id}/unmask",
    label: "required params",
    run: -> { client.representatives.list_unmasked("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/representatives/{representative_id}/unmask",
    label: "all params",
    run: -> do
      client.representatives.list_unmasked(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {correlation_id: "correlation_id", request_id: "request_id"}
      )
    end
  },
  {
    operation: "createBankAccountPaykey",
    method: "POST",
    path: "/v1/bridge/bank_account",
    label: "required params",
    run: -> do
      client.bridge.create_bank_account_paykey(
        {
          account_number: "",
          account_type: "checking",
          customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          routing_number: "xxxxxxxxx"
        }
      )
    end
  },
  {
    operation: "createBankAccountPaykey",
    method: "POST",
    path: "/v1/bridge/bank_account",
    label: "all params",
    run: -> do
      client.bridge.create_bank_account_paykey(
        {
          account_number: "",
          account_type: "checking",
          customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          routing_number: "xxxxxxxxx",
          config: {
            "sandbox_outcome" => "standard",
            "processing_method" => "inline"
          },
          external_id: "",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "createPlaidPaykey",
    method: "POST",
    path: "/v1/bridge/plaid",
    label: "required params",
    run: -> do
      client.bridge.create_plaid_paykey(
        {customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7", plaid_token: ""}
      )
    end
  },
  {
    operation: "createPlaidPaykey",
    method: "POST",
    path: "/v1/bridge/plaid",
    label: "all params",
    run: -> do
      client.bridge.create_plaid_paykey(
        {
          customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          plaid_token: "",
          config: {
            "sandbox_outcome" => "standard",
            "processing_method" => "inline"
          },
          external_id: "",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "createQuilttPaykey",
    method: "POST",
    path: "/v1/bridge/quiltt",
    label: "required params",
    run: -> do
      client.bridge.create_quiltt_paykey(
        {customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7", quiltt_token: ""}
      )
    end
  },
  {
    operation: "createQuilttPaykey",
    method: "POST",
    path: "/v1/bridge/quiltt",
    label: "all params",
    run: -> do
      client.bridge.create_quiltt_paykey(
        {
          customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          quiltt_token: "",
          config: {
            "sandbox_outcome" => "standard",
            "processing_method" => "inline"
          },
          external_id: "",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "createToken",
    method: "POST",
    path: "/v1/bridge/initialize",
    label: "required params",
    run: -> { client.bridge.create_token({customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"}) }
  },
  {
    operation: "createToken",
    method: "POST",
    path: "/v1/bridge/initialize",
    label: "all params",
    run: -> do
      client.bridge.create_token(
        {
          customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          config: {
            "sandbox_outcome" => "standard",
            "processing_method" => "inline"
          },
          external_id: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/customers",
    label: "required params",
    run: -> do
      client.customers.create(
        {
          device: {
            "ip_address" => "192.168.1.1"
          },
          email: "ron.swanson@pawnee.com",
          name: "Ron Swanson",
          phone: "+12128675309",
          type: "individual",
          address: {
            "address1" => "123 Main St",
            "city" => "Anytown",
            "state" => "CA",
            "zip" => "94105"
          },
          external_id: "customer_123",
          metadata: {}
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/customers",
    label: "all params",
    run: -> do
      client.customers.create(
        {
          device: {
            "ip_address" => "192.168.1.1"
          },
          email: "ron.swanson@pawnee.com",
          name: "Ron Swanson",
          phone: "+12128675309",
          type: "individual",
          address: {
            "address1" => "123 Main St",
            "city" => "Anytown",
            "state" => "CA",
            "zip" => "94105"
          },
          compliance_profile: StringIO.new("smoke-test"),
          config: {
            "sandbox_outcome" => "standard",
            "processing_method" => "inline"
          },
          external_id: "customer_123",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/customers/{id}",
    label: "required params",
    run: -> { client.customers.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/customers/{id}",
    label: "all params",
    run: -> do
      client.customers.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/customers/{id}",
    label: "required params",
    run: -> do
      client.customers.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          device: {
            "ip_address" => "192.168.1.1"
          },
          email: "user@example.com",
          name: "",
          phone: "",
          status: "verified"
        }
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/customers/{id}",
    label: "all params",
    run: -> do
      client.customers.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          device: {
            "ip_address" => "192.168.1.1"
          },
          email: "user@example.com",
          name: "",
          phone: "",
          status: "verified",
          address: {
            "address1" => "123 Main St",
            "address2" => "Apt 1",
            "city" => "Anytown",
            "state" => "CA",
            "zip" => "12345"
          },
          compliance_profile: StringIO.new("smoke-test"),
          external_id: "",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/customers",
    label: "required params",
    run: -> { client.customers.list({page_number: 1, page_size: 100, sort_order: "asc"}) }
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/customers",
    label: "all params",
    run: -> do
      client.customers.list(
        {
          created_from: "2024-01-01T00:00:00.000Z",
          created_to: "2024-01-01T00:00:00.000Z",
          email: "email",
          external_id: "external_id",
          name: "name",
          page_number: 1,
          page_size: 100,
          search_text: "search_text",
          sort_by: "name",
          sort_order: "asc",
          status: ["pending"],
          types: ["individual"],
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/customers/{id}",
    label: "required params",
    run: -> { client.customers.delete("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "delete",
    method: "DELETE",
    path: "/v1/customers/{id}",
    label: "all params",
    run: -> do
      client.customers.delete(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/customers/{id}/unmasked",
    label: "required params",
    run: -> { client.customers.list_unmasked("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/customers/{id}/unmasked",
    label: "all params",
    run: -> do
      client.customers.list_unmasked(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "refreshReview",
    method: "PUT",
    path: "/v1/customers/{id}/refresh_review",
    label: "required params",
    run: -> { client.customers.refresh_review("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "refreshReview",
    method: "PUT",
    path: "/v1/customers/{id}/refresh_review",
    label: "all params",
    run: -> do
      client.customers.refresh_review(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/customers/{id}/review",
    label: "required params",
    run: -> { client.customers.review.list("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/customers/{id}/review",
    label: "all params",
    run: -> do
      client.customers.review.list(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "setVerificationDecision",
    method: "PATCH",
    path: "/v1/customers/{id}/review",
    label: "required params",
    run: -> do
      client.customers.review.set_verification_decision(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {status: "verified"}
      )
    end
  },
  {
    operation: "setVerificationDecision",
    method: "PATCH",
    path: "/v1/customers/{id}/review",
    label: "all params",
    run: -> do
      client.customers.review.set_verification_decision(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          status: "verified",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/paykeys/{id}",
    label: "required params",
    run: -> { client.paykeys.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/paykeys/{id}",
    label: "all params",
    run: -> do
      client.paykeys.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/paykeys",
    label: "required params",
    run: -> { client.paykeys.list({page_number: 1, page_size: 100, sort_order: "asc"}) }
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/paykeys",
    label: "all params",
    run: -> do
      client.paykeys.list(
        {
          created_from: "2024-01-01T00:00:00.000Z",
          created_to: "2024-01-01T00:00:00.000Z",
          customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          page_number: 1,
          page_size: 100,
          search_text: "search_text",
          sort_by: "institution_name",
          sort_order: "asc",
          source: ["bank_account"],
          status: ["pending"],
          unblock_eligible: true,
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "cancel",
    method: "PUT",
    path: "/v1/paykeys/{id}/cancel",
    label: "required params",
    run: -> { client.paykeys.cancel("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "cancel",
    method: "PUT",
    path: "/v1/paykeys/{id}/cancel",
    label: "all params",
    run: -> do
      client.paykeys.cancel(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          reason: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/paykeys/{id}/unmasked",
    label: "required params",
    run: -> { client.paykeys.list_unmasked("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/paykeys/{id}/unmasked",
    label: "all params",
    run: -> do
      client.paykeys.list_unmasked(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "refreshBalance",
    method: "PUT",
    path: "/v1/paykeys/{id}/refresh_balance",
    label: "required params",
    run: -> { client.paykeys.refresh_balance("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "refreshBalance",
    method: "PUT",
    path: "/v1/paykeys/{id}/refresh_balance",
    label: "all params",
    run: -> do
      client.paykeys.refresh_balance(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "refreshReview",
    method: "PUT",
    path: "/v1/paykeys/{id}/refresh_review",
    label: "required params",
    run: -> { client.paykeys.refresh_review("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "refreshReview",
    method: "PUT",
    path: "/v1/paykeys/{id}/refresh_review",
    label: "all params",
    run: -> do
      client.paykeys.refresh_review(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "reveal",
    method: "GET",
    path: "/v1/paykeys/{id}/reveal",
    label: "required params",
    run: -> { client.paykeys.reveal("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "reveal",
    method: "GET",
    path: "/v1/paykeys/{id}/reveal",
    label: "all params",
    run: -> do
      client.paykeys.reveal(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "unblock",
    method: "PATCH",
    path: "/v1/paykeys/{id}/unblock",
    label: "required params",
    run: -> { client.paykeys.unblock("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "unblock",
    method: "PATCH",
    path: "/v1/paykeys/{id}/unblock",
    label: "all params",
    run: -> do
      client.paykeys.unblock(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          message: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/paykeys/{id}/review",
    label: "required params",
    run: -> { client.paykeys.review.list("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/paykeys/{id}/review",
    label: "all params",
    run: -> do
      client.paykeys.review.list(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "setVerificationDecision",
    method: "PATCH",
    path: "/v1/paykeys/{id}/review",
    label: "required params",
    run: -> do
      client.paykeys.review.set_verification_decision(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {status: "active"}
      )
    end
  },
  {
    operation: "setVerificationDecision",
    method: "PATCH",
    path: "/v1/paykeys/{id}/review",
    label: "all params",
    run: -> do
      client.paykeys.review.set_verification_decision(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          status: "active",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/charges",
    label: "required params",
    run: -> do
      client.charges.create(
        {
          amount: 10_000,
          config: {
            "balance_check" => "enabled"
          },
          consent_type: "internet",
          currency: "USD",
          description: "Monthly subscription fee",
          device: {
            "ip_address" => "192.168.1.1"
          },
          external_id: "",
          paykey: "",
          payment_date: "2024-01-01"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/charges",
    label: "all params",
    run: -> do
      client.charges.create(
        {
          amount: 10_000,
          config: {
            "balance_check" => "enabled",
            "sandbox_outcome" => "standard",
            "auto_hold" => false,
            "auto_hold_message" => ""
          },
          consent_type: "internet",
          currency: "USD",
          description: "Monthly subscription fee",
          device: {
            "ip_address" => "192.168.1.1"
          },
          external_id: "",
          paykey: "",
          payment_date: "2024-01-01",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/charges/{id}",
    label: "required params",
    run: -> { client.charges.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/charges/{id}",
    label: "all params",
    run: -> do
      client.charges.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/charges/{id}",
    label: "required params",
    run: -> do
      client.charges.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {amount: 10_000, description: "Monthly subscription fee", payment_date: "2024-01-01"}
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/charges/{id}",
    label: "all params",
    run: -> do
      client.charges.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          amount: 10_000,
          description: "Monthly subscription fee",
          payment_date: "2024-01-01",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "cancel",
    method: "PUT",
    path: "/v1/charges/{id}/cancel",
    label: "required params",
    run: -> { client.charges.cancel("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "cancel",
    method: "PUT",
    path: "/v1/charges/{id}/cancel",
    label: "all params",
    run: -> do
      client.charges.cancel(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          reason: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "hold",
    method: "PUT",
    path: "/v1/charges/{id}/hold",
    label: "required params",
    run: -> { client.charges.hold("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "hold",
    method: "PUT",
    path: "/v1/charges/{id}/hold",
    label: "all params",
    run: -> do
      client.charges.hold(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          reason: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/charges/{id}/unmask",
    label: "required params",
    run: -> { client.charges.list_unmasked("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/charges/{id}/unmask",
    label: "all params",
    run: -> do
      client.charges.list_unmasked(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "refund",
    method: "POST",
    path: "/v1/charges/{id}/refund",
    label: "required params",
    run: -> { client.charges.refund("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "refund",
    method: "POST",
    path: "/v1/charges/{id}/refund",
    label: "all params",
    run: -> do
      client.charges.refund(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          amount: 5000,
          description: "",
          external_id: "",
          metadata: {},
          payment_date: "2024-01-01",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "release",
    method: "PUT",
    path: "/v1/charges/{id}/release",
    label: "required params",
    run: -> { client.charges.release("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "release",
    method: "PUT",
    path: "/v1/charges/{id}/release",
    label: "all params",
    run: -> do
      client.charges.release(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          reason: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "resubmit",
    method: "POST",
    path: "/v1/charges/{id}/resubmit",
    label: "required params",
    run: -> { client.charges.resubmit("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "resubmit",
    method: "POST",
    path: "/v1/charges/{id}/resubmit",
    label: "all params",
    run: -> do
      client.charges.resubmit(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          description: "",
          external_id: "",
          payment_date: "2024-01-01",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "uploadAuthorizationProof",
    method: "POST",
    path: "/v1/charges/{id}/authorization",
    label: "required params",
    run: -> do
      client.charges.upload_authorization_proof("7c9e6679-7425-40de-944b-e07fc1f90ae7", {file: ""})
    end
  },
  {
    operation: "uploadAuthorizationProof",
    method: "POST",
    path: "/v1/charges/{id}/authorization",
    label: "all params",
    run: -> do
      client.charges.upload_authorization_proof(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          file: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/funding_events/{id}",
    label: "required params",
    run: -> { client.funding_events.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/funding_events/{id}",
    label: "all params",
    run: -> do
      client.funding_events.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/funding_events",
    label: "required params",
    run: -> { client.funding_events.list({page_number: 1, page_size: 100, sort_order: "asc"}) }
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/funding_events",
    label: "all params",
    run: -> do
      client.funding_events.list(
        {
          created_from: "2024-01-01",
          created_to: "2024-01-01",
          direction: "deposit",
          event_type: "charge_deposit",
          page_number: 1,
          page_size: 100,
          search_text: "search_text",
          sort_by: "transfer_date",
          sort_order: "asc",
          status: ["created"],
          status_reason: ["insufficient_funds"],
          status_source: ["watchtower"],
          trace_id: "trace_id",
          trace_number: "trace_number",
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "listPayments",
    method: "GET",
    path: "/v1/funding_event_payments/{id}",
    label: "required params",
    run: -> do
      client.funding_events.list_payments(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {default_sort_order: "asc", sort_order: "asc"}
      )
    end
  },
  {
    operation: "listPayments",
    method: "GET",
    path: "/v1/funding_event_payments/{id}",
    label: "all params",
    run: -> do
      client.funding_events.list_payments(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          default_page_size: 1,
          default_sort: "created_at",
          default_sort_order: "asc",
          include_metadata: true,
          page_number: 1,
          page_size: 1,
          sort_by: "created_at",
          sort_order: "asc",
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "simulate",
    method: "POST",
    path: "/v1/funding_events/simulate",
    label: "required params",
    run: -> { client.funding_events.simulate({funding_event_job_type: "charges"}) }
  },
  {
    operation: "simulate",
    method: "POST",
    path: "/v1/funding_events/simulate",
    label: "all params",
    run: -> do
      client.funding_events.simulate(
        {
          funding_event_job_type: "charges",
          sandbox_outcome: "standard",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/payments",
    label: "required params",
    run: -> do
      client.payments.list(
        {
          default_sort: "id",
          default_sort_order: "asc",
          page_number: 1,
          page_size: 100,
          sort_by: "id",
          sort_order: "asc"
        }
      )
    end
  },
  {
    operation: "list",
    method: "GET",
    path: "/v1/payments",
    label: "all params",
    run: -> do
      client.payments.list(
        {
          customer_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          default_page_size: 1,
          default_sort: "id",
          default_sort_order: "asc",
          external_id: "external_id",
          funding_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          has_refund: true,
          has_resubmit: true,
          include_metadata: true,
          is_refund: true,
          is_resubmit: true,
          max_amount: 1,
          max_created_at: "2024-01-01T00:00:00.000Z",
          max_effective_at: "2024-01-01T00:00:00.000Z",
          max_payment_date: "2024-01-01",
          max_updated_at: "2024-01-01T00:00:00.000Z",
          min_amount: 1,
          min_created_at: "2024-01-01T00:00:00.000Z",
          min_effective_at: "2024-01-01T00:00:00.000Z",
          min_payment_date: "2024-01-01",
          min_updated_at: "2024-01-01T00:00:00.000Z",
          page_number: 1,
          page_size: 100,
          paykey: "paykey",
          paykey_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          payment_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
          payment_status: ["created"],
          payment_type: ["charge"],
          search_text: "search_text",
          sort_by: "id",
          sort_order: "asc",
          status_reason: ["insufficient_funds"],
          status_source: ["watchtower"],
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/payouts",
    label: "required params",
    run: -> do
      client.payouts.create(
        {
          amount: 10_000,
          currency: "USD",
          description: "Vendor invoice payment",
          device: {
            "ip_address" => "192.168.1.1"
          },
          external_id: "",
          paykey: "",
          payment_date: "2024-01-01"
        }
      )
    end
  },
  {
    operation: "create",
    method: "POST",
    path: "/v1/payouts",
    label: "all params",
    run: -> do
      client.payouts.create(
        {
          amount: 10_000,
          currency: "USD",
          description: "Vendor invoice payment",
          device: {
            "ip_address" => "192.168.1.1"
          },
          external_id: "",
          paykey: "",
          payment_date: "2024-01-01",
          config: {
            "sandbox_outcome" => "standard",
            "auto_hold" => false,
            "auto_hold_message" => ""
          },
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/payouts/{id}",
    label: "required params",
    run: -> { client.payouts.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/payouts/{id}",
    label: "all params",
    run: -> do
      client.payouts.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/payouts/{id}",
    label: "required params",
    run: -> do
      client.payouts.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {amount: 10_000, description: "", payment_date: "2024-01-01"}
      )
    end
  },
  {
    operation: "update",
    method: "PUT",
    path: "/v1/payouts/{id}",
    label: "all params",
    run: -> do
      client.payouts.update(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          amount: 10_000,
          description: "",
          payment_date: "2024-01-01",
          metadata: {},
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "cancel",
    method: "PUT",
    path: "/v1/payouts/{id}/cancel",
    label: "required params",
    run: -> { client.payouts.cancel("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "cancel",
    method: "PUT",
    path: "/v1/payouts/{id}/cancel",
    label: "all params",
    run: -> do
      client.payouts.cancel(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          reason: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "hold",
    method: "PUT",
    path: "/v1/payouts/{id}/hold",
    label: "required params",
    run: -> { client.payouts.hold("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "hold",
    method: "PUT",
    path: "/v1/payouts/{id}/hold",
    label: "all params",
    run: -> do
      client.payouts.hold(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          reason: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/payouts/{id}/unmask",
    label: "required params",
    run: -> { client.payouts.list_unmasked("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "listUnmasked",
    method: "GET",
    path: "/v1/payouts/{id}/unmask",
    label: "all params",
    run: -> do
      client.payouts.list_unmasked(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          correlation_id: "correlation_id",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "release",
    method: "PUT",
    path: "/v1/payouts/{id}/release",
    label: "required params",
    run: -> { client.payouts.release("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "release",
    method: "PUT",
    path: "/v1/payouts/{id}/release",
    label: "all params",
    run: -> do
      client.payouts.release(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          reason: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "resubmit",
    method: "POST",
    path: "/v1/payouts/{id}/resubmit",
    label: "required params",
    run: -> { client.payouts.resubmit("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "resubmit",
    method: "POST",
    path: "/v1/payouts/{id}/resubmit",
    label: "all params",
    run: -> do
      client.payouts.resubmit(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          description: "",
          external_id: "",
          payment_date: "2024-01-01",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "uploadAuthorizationProof",
    method: "POST",
    path: "/v1/payouts/{id}/authorization",
    label: "required params",
    run: -> do
      client.payouts.upload_authorization_proof("7c9e6679-7425-40de-944b-e07fc1f90ae7", {file: ""})
    end
  },
  {
    operation: "uploadAuthorizationProof",
    method: "POST",
    path: "/v1/payouts/{id}/authorization",
    label: "all params",
    run: -> do
      client.payouts.upload_authorization_proof(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {
          file: "",
          correlation_id: "correlation_id",
          idempotency_key: "idempotency_key",
          request_id: "request_id",
          straddle_account_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        }
      )
    end
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/account_settings/{account_id}",
    label: "required params",
    run: -> { client.account_settings.retrieve("7c9e6679-7425-40de-944b-e07fc1f90ae7") }
  },
  {
    operation: "retrieve",
    method: "GET",
    path: "/v1/account_settings/{account_id}",
    label: "all params",
    run: -> do
      client.account_settings.retrieve(
        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
        {correlation_id: "correlation_id", request_id: "request_id"}
      )
    end
  }
]

def run_case(test_case)
  started_at = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  # `label` distinguishes the required-params run from the all-params run of the same operation;
  # it is absent entirely when the operation contributed only one case.
  identity = {operation: test_case[:operation], method: test_case[:method], path: test_case[:path]}
  identity[:label] = test_case[:label] if test_case[:label]
  begin
    test_case[:run].call
    identity.merge(
      status: "passed",
      durationMs: ((Process.clock_gettime(Process::CLOCK_MONOTONIC) - started_at) * 1000).to_i
    )
  rescue StandardError => e
    identity.merge(
      status: "failed",
      durationMs: ((Process.clock_gettime(Process::CLOCK_MONOTONIC) - started_at) * 1000).to_i,
      error: ([e.class.name, e.message] + e.backtrace.to_a).join("\n")
    )
  end
end

filter = ENV["SCALAR_SMOKE_FILTER"]
needles = filter ? filter.split(",").map(&:strip).reject(&:empty?) : []
selected =
  (
    if needles.empty?
      cases
    else
      cases.select do |test_case|
        needles.any? { |needle| test_case[:operation].include?(needle) || test_case[:path].include?(needle) }
      end
    end
  )

results =
  selected.map { |test_case| Thread.new(test_case) { |smoke_case| run_case(smoke_case) } }.map(&:value)

failed = results.select { |result| result[:status] == "failed" }
if ENV["SCALAR_SMOKE_REPORT"]
  File.write(
    ENV.fetch("SCALAR_SMOKE_REPORT"),
    JSON.generate({total: results.length, failed: failed.length, results: results})
  )
else
  results.each do |result|
    suffix = result[:label] ? " [#{result[:label]}]" : ""
    if result[:status] == "passed"
      puts "PASS #{result[:operation]}#{suffix} (#{result[:method]} #{result[:path]}) #{result[:durationMs]}ms"
    else
      warn "FAIL #{result[:operation]}#{suffix} (#{result[:method]} #{result[:path]})\n#{result[:error]}"
    end
  end
  warn "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing)." if results.empty?
  puts "\n#{results.length - failed.length}/#{results.length} samples passed" unless results.empty?
end

exit(1) if failed.any? || results.empty?
