module Straddle
  module Resources
    class Organizations
      def create: (
        name: String,
        ?external_id: String?,
        ?metadata: ::Hash[Symbol, String?]?,
        ?correlation_id: String,
        ?idempotency_key: String,
        ?request_id: String,
        ?request_options: Straddle::request_opts
      ) -> Straddle::OrganizationResponse

      def retrieve: (
        String organization_id,
        ?correlation_id: String,
        ?request_id: String,
        ?request_options: Straddle::request_opts
      ) -> Straddle::OrganizationResponse

      def list: (
        ?external_id: String,
        ?name: String,
        ?page_number: Integer,
        ?page_size: Integer,
        ?sort_by: String,
        ?sort_order: Straddle::Models::OrganizationListParams::sort_order,
        ?correlation_id: String,
        ?request_id: String,
        ?request_options: Straddle::request_opts
      ) -> Straddle::OrganizationList

      def initialize: (client: Straddle::Client) -> void
    end
  end
end
