# typed: strong

module Straddle
  module Resources
    # Bridge connects customer bank accounts and creates paykeys from supported
    # provider tokens or bank account details.
    class Bridge
      # Creates a paykey from a routing number, account number, and account type.
      sig do
        params(
          account_number: String,
          account_type: Straddle::AccountType::OrSymbol,
          customer_id: String,
          routing_number: String,
          config: Straddle::PaykeyConfiguration::OrHash,
          external_id: T.nilable(String),
          metadata: T.nilable(T::Hash[Symbol, String]),
          correlation_id: String,
          idempotency_key: String,
          request_id: String,
          straddle_account_id: String,
          request_options: Straddle::RequestOptions::OrHash
        ).returns(Straddle::PaykeyResponse)
      end
      def create_bank_account_paykey(
        # Body param: Bank account number.
        account_number:,
        # Body param
        account_type:,
        # Body param: Unique identifier for the customer associated with the paykey.
        customer_id:,
        # Body param: Bank routing number.
        routing_number:,
        # Body param
        config: nil,
        # Body param: Unique identifier for the paykey in your system.
        external_id: nil,
        # Body param: Up to 20 user-defined key-value pairs associated with the paykey.
        metadata: nil,
        # Header param: Optional client-generated identifier for tracing a series of
        # related requests.
        correlation_id: nil,
        # Header param: Optional client-generated key for an idempotent request.
        idempotency_key: nil,
        # Header param: Optional client-generated identifier for tracing one request.
        request_id: nil,
        # Header param: For platform requests, the embedded account UUID that sets the
        # request scope.
        straddle_account_id: nil,
        request_options: {}
      )
      end

      # Creates a paykey from a Plaid processor token.
      sig do
        params(
          customer_id: String,
          plaid_token: String,
          config: Straddle::PaykeyConfiguration::OrHash,
          external_id: T.nilable(String),
          metadata: T.nilable(T::Hash[Symbol, String]),
          correlation_id: String,
          idempotency_key: String,
          request_id: String,
          straddle_account_id: String,
          request_options: Straddle::RequestOptions::OrHash
        ).returns(Straddle::PaykeyResponse)
      end
      def create_plaid_paykey(
        # Body param: Unique identifier for the customer associated with the paykey.
        customer_id:,
        # Body param: Plaid processor token generated by your application for use with the
        # Straddle API.
        plaid_token:,
        # Body param
        config: nil,
        # Body param: Unique identifier for the paykey in your system.
        external_id: nil,
        # Body param: Up to 20 user-defined key-value pairs associated with the paykey.
        metadata: nil,
        # Header param: Optional client-generated identifier for tracing a series of
        # related requests.
        correlation_id: nil,
        # Header param: Optional client-generated key for an idempotent request.
        idempotency_key: nil,
        # Header param: Optional client-generated identifier for tracing one request.
        request_id: nil,
        # Header param: For platform requests, the embedded account UUID that sets the
        # request scope.
        straddle_account_id: nil,
        request_options: {}
      )
      end

      # Creates a paykey from a Quiltt processor token.
      sig do
        params(
          customer_id: String,
          quiltt_token: String,
          config: Straddle::PaykeyConfiguration::OrHash,
          external_id: T.nilable(String),
          metadata: T.nilable(T::Hash[Symbol, String]),
          correlation_id: String,
          idempotency_key: String,
          request_id: String,
          straddle_account_id: String,
          request_options: Straddle::RequestOptions::OrHash
        ).returns(Straddle::RevealedPaykeyResponse)
      end
      def create_quiltt_paykey(
        # Body param: Unique identifier for the customer associated with the paykey.
        customer_id:,
        # Body param: Quiltt processor token generated by your application for use with
        # the Straddle API.
        quiltt_token:,
        # Body param
        config: nil,
        # Body param: Unique identifier for the paykey in your system.
        external_id: nil,
        # Body param: Up to 20 user-defined key-value pairs associated with the paykey.
        metadata: nil,
        # Header param: Optional client-generated identifier for tracing a series of
        # related requests.
        correlation_id: nil,
        # Header param: Optional client-generated key for an idempotent request.
        idempotency_key: nil,
        # Header param: Optional client-generated identifier for tracing one request.
        request_id: nil,
        # Header param: For platform requests, the embedded account UUID that sets the
        # request scope.
        straddle_account_id: nil,
        request_options: {}
      )
      end

      # Creates a session token for the Bridge widget.
      sig do
        params(
          customer_id: String,
          config: Straddle::PaykeyConfiguration::OrHash,
          external_id: T.nilable(String),
          correlation_id: String,
          idempotency_key: String,
          request_id: String,
          straddle_account_id: String,
          request_options: Straddle::RequestOptions::OrHash
        ).returns(Straddle::BridgeTokenResponse)
      end
      def create_token(
        # Body param: Unique identifier for the customer associated with the Bridge
        # session.
        customer_id:,
        # Body param
        config: nil,
        # Body param: Unique identifier for the paykey in your system.
        external_id: nil,
        # Header param: Optional client-generated identifier for tracing a series of
        # related requests.
        correlation_id: nil,
        # Header param: Optional client-generated key for an idempotent request.
        idempotency_key: nil,
        # Header param: Optional client-generated identifier for tracing one request.
        request_id: nil,
        # Header param: For platform requests, the embedded account UUID that sets the
        # request scope.
        straddle_account_id: nil,
        request_options: {}
      )
      end

      # @api private
      sig { params(client: Straddle::Client).returns(T.attached_class) }
      def self.new(client:)
      end
    end
  end
end
