module Straddle
  module Models
    module Customers
      type identity_verification_breakdown =
        {
          codes: ::Array[String]?,
          correlation: Straddle::Models::Customers::correlation_bucket,
          correlation_score: Float?,
          decision: Straddle::Models::Customers::verification_decision,
          risk_score: Float?
        }

      class IdentityVerificationBreakdown < Straddle::Internal::Type::BaseModel
        attr_accessor codes: ::Array[String]?

        attr_reader correlation: Straddle::Models::Customers::correlation_bucket?

        def correlation=: (
          Straddle::Models::Customers::correlation_bucket
        ) -> Straddle::Models::Customers::correlation_bucket

        attr_accessor correlation_score: Float?

        attr_reader decision: Straddle::Models::Customers::verification_decision?

        def decision=: (
          Straddle::Models::Customers::verification_decision
        ) -> Straddle::Models::Customers::verification_decision

        attr_accessor risk_score: Float?

        def initialize: (
          ?codes: ::Array[String]?,
          ?correlation: Straddle::Models::Customers::correlation_bucket,
          ?correlation_score: Float?,
          ?decision: Straddle::Models::Customers::verification_decision,
          ?risk_score: Float?
        ) -> void

        def to_hash: -> {
          codes: ::Array[String]?,
          correlation: Straddle::Models::Customers::correlation_bucket,
          correlation_score: Float?,
          decision: Straddle::Models::Customers::verification_decision,
          risk_score: Float?
        }
      end
    end
  end
end
