module Straddle
  module Models
    class PaykeyReviewResponse = Paykeys::PaykeyReviewResponse

    module Paykeys
      type paykey_review_response =
        {
          data: Straddle::Paykeys::PaykeyReview,
          meta: Straddle::ResponseMetadata,
          response_type: Straddle::Models::response_type
        }

      class PaykeyReviewResponse < Straddle::Internal::Type::BaseModel
        attr_accessor data: Straddle::Paykeys::PaykeyReview

        attr_accessor meta: Straddle::ResponseMetadata

        attr_accessor response_type: Straddle::Models::response_type

        def initialize: (
          data: Straddle::Paykeys::PaykeyReview,
          meta: Straddle::ResponseMetadata,
          response_type: Straddle::Models::response_type
        ) -> void

        def to_hash: -> {
          data: Straddle::Paykeys::PaykeyReview,
          meta: Straddle::ResponseMetadata,
          response_type: Straddle::Models::response_type
        }
      end
    end
  end
end
